name: Deploy WordPress plugin
on:
  push:
    branches: [ master, 'release/v[0-9].[0-9].[0-9]' ]

jobs:
  build:
    name: Deploy WordPress plugin
    # 2. Specify Linux runner
    runs-on: ubuntu-20.04
    steps:
      # 3. Checkout before Use this deployment action
      - name: Checkout
        uses: actions/checkout@v3
      # 4. Use action with environment variable set by secrets
      - name: Deploy
        uses: yukihiko-shinoda/action-deploy-wordpress-plugin@v2.1.1
        env:
          SVN_REPOSITORY_URL: ${{ secrets.SVN_REPO_URL }}
          SVN_USER_NAME: ${{ secrets.SVN_USERNAME }}
          SVN_USER_PASSWORD: ${{ secrets.SVN_PASSWORD }}
